var CONFIG = CONFIG || {};
CONFIG.GAME_STATE = {
    HOME:0,
    PLAY:1,
    OVER:2
};
CONFIG.MAXLEVEL = 4;

CONFIG.DELAY_PERUNIT = 1/8;


CONFIG.ZORDER = {
    ENEMY: 300,
    GAMEBOARD: 100,
    SPIKE: 200,
    PLAYER: 400
};

CONFIG.MAPSIZE = [7,7]
CONFIG.SCALE = {
    FLOOR: 3.5,
    PERSON: 2.5,
}

CONFIG.BARRIER_SIZE = [5, 6, 7];
CONFIG.VELOCITY = {
    PLAYER: 0.3,
    ENEMIES: [0.3, 0.3, 0.3],

}
CONFIG.LEVEL_SIZE = {
    LEVEL1: [3, 4],
    LEVEL2: [4, 5],
    LEVEL3: [5, 6],
    LEVEL4: [6, 7]
}

CONFIG.SCORE = 0;

CONFIG.SOUND = true;

CONFIG.CONTAINER = {
    ENEMIES: [],
    BARRIERS: [],
    PLAYERS: [],
    PRINCESS: [],
    SWORDS: []
}

CONFIG.BUTTON_SIZE = [500, 131];

CONFIG.ENEMY_NAME = ["Demon", "Executioner", "Thief"];
CONFIG.ENEMIES_SIZE = [1, 2, 3];


